Resources:
  CreateMahabaratAWSResourcesmultipurposeapilambdamahabharatgetcharactermapServiceRole5D00E6BD:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
        Version: "2012-10-17"
      ManagedPolicyArns:
        - Fn::Join:
            - ""
            - - "arn:"
              - Ref: AWS::Partition
              - :iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
    Metadata:
      aws:cdk:path: CreateMahabaratAWSResourcesStack/CreateMahabaratAWSResources/multipurpose-api-lambda-mahabharat-getcharactermap/ServiceRole/Resource
  CreateMahabaratAWSResourcesmultipurposeapilambdamahabharatgetcharactermap0A63BDCC:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket:
          Ref: AssetParameters50e5446594261ec166609ce16e76ca70754ddbb6a26eabee651fc1fae286d403S3Bucket5D28E9B0
        S3Key:
          Fn::Join:
            - ""
            - - Fn::Select:
                  - 0
                  - Fn::Split:
                      - "||"
                      - Ref: AssetParameters50e5446594261ec166609ce16e76ca70754ddbb6a26eabee651fc1fae286d403S3VersionKey4A90999D
              - Fn::Select:
                  - 1
                  - Fn::Split:
                      - "||"
                      - Ref: AssetParameters50e5446594261ec166609ce16e76ca70754ddbb6a26eabee651fc1fae286d403S3VersionKey4A90999D
      Handler: lib/getCharacterMap.GetCharacterMap
      Role:
        Fn::GetAtt:
          - CreateMahabaratAWSResourcesmultipurposeapilambdamahabharatgetcharactermapServiceRole5D00E6BD
          - Arn
      Runtime: nodejs12.x
      FunctionName: multipurpose-api-lambda-mahabharat-getcharactermap
      MemorySize: 128
      Timeout: 5
    DependsOn:
      - CreateMahabaratAWSResourcesmultipurposeapilambdamahabharatgetcharactermapServiceRole5D00E6BD
    Metadata:
      aws:cdk:path: CreateMahabaratAWSResourcesStack/CreateMahabaratAWSResources/multipurpose-api-lambda-mahabharat-getcharactermap/Resource
      aws:asset:path: asset.50e5446594261ec166609ce16e76ca70754ddbb6a26eabee651fc1fae286d403.zip
      aws:asset:property: Code
  CreateMahabaratAWSResourcesmahabharatapi873664F6:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: mahabharat-api
    Metadata:
      aws:cdk:path: CreateMahabaratAWSResourcesStack/CreateMahabaratAWSResources/mahabharat-api/Resource
  CreateMahabaratAWSResourcesmahabharatapiCloudWatchRole69C622B3:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: apigateway.amazonaws.com
        Version: "2012-10-17"
      ManagedPolicyArns:
        - Fn::Join:
            - ""
            - - "arn:"
              - Ref: AWS::Partition
              - :iam::aws:policy/service-role/AmazonAPIGatewayPushToCloudWatchLogs
    Metadata:
      aws:cdk:path: CreateMahabaratAWSResourcesStack/CreateMahabaratAWSResources/mahabharat-api/CloudWatchRole/Resource
  CreateMahabaratAWSResourcesmahabharatapiAccount99010E3D:
    Type: AWS::ApiGateway::Account
    Properties:
      CloudWatchRoleArn:
        Fn::GetAtt:
          - CreateMahabaratAWSResourcesmahabharatapiCloudWatchRole69C622B3
          - Arn
    DependsOn:
      - CreateMahabaratAWSResourcesmahabharatapi873664F6
    Metadata:
      aws:cdk:path: CreateMahabaratAWSResourcesStack/CreateMahabaratAWSResources/mahabharat-api/Account
  CreateMahabaratAWSResourcesmahabharatapiDeploymentECAC2EFEf78ffe857612a0b7a13f76301796122c:
    Type: AWS::ApiGateway::Deployment
    Properties:
      RestApiId:
        Ref: CreateMahabaratAWSResourcesmahabharatapi873664F6
      Description: Automatically created by the RestApi construct
    DependsOn:
      - CreateMahabaratAWSResourcesmahabharatapimahabharatcharactermapGET1B49E0BC
      - CreateMahabaratAWSResourcesmahabharatapimahabharatcharactermapEB3E8AE3
    Metadata:
      aws:cdk:path: CreateMahabaratAWSResourcesStack/CreateMahabaratAWSResources/mahabharat-api/Deployment/Resource
  CreateMahabaratAWSResourcesmahabharatapiDeploymentStageprod79B2FA4E:
    Type: AWS::ApiGateway::Stage
    Properties:
      RestApiId:
        Ref: CreateMahabaratAWSResourcesmahabharatapi873664F6
      DeploymentId:
        Ref: CreateMahabaratAWSResourcesmahabharatapiDeploymentECAC2EFEf78ffe857612a0b7a13f76301796122c
      StageName: prod
    Metadata:
      aws:cdk:path: CreateMahabaratAWSResourcesStack/CreateMahabaratAWSResources/mahabharat-api/DeploymentStage.prod/Resource
  CreateMahabaratAWSResourcesmahabharatapimahabharatcharactermapEB3E8AE3:
    Type: AWS::ApiGateway::Resource
    Properties:
      ParentId:
        Fn::GetAtt:
          - CreateMahabaratAWSResourcesmahabharatapi873664F6
          - RootResourceId
      PathPart: mahabharat-character-map
      RestApiId:
        Ref: CreateMahabaratAWSResourcesmahabharatapi873664F6
    Metadata:
      aws:cdk:path: CreateMahabaratAWSResourcesStack/CreateMahabaratAWSResources/mahabharat-api/Default/mahabharat-character-map/Resource
  CreateMahabaratAWSResourcesmahabharatapimahabharatcharactermapGETApiPermissionCreateMahabaratAWSResourcesStackCreateMahabaratAWSResourcesmahabharatapiCBFC22B3GETmahabharatcharactermapC73958E2:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName:
        Fn::GetAtt:
          - CreateMahabaratAWSResourcesmultipurposeapilambdamahabharatgetcharactermap0A63BDCC
          - Arn
      Principal: apigateway.amazonaws.com
      SourceArn:
        Fn::Join:
          - ""
          - - "arn:"
            - Ref: AWS::Partition
            - ":execute-api:ap-southeast-2:"
            - Ref: AWS::AccountId
            - ":"
            - Ref: CreateMahabaratAWSResourcesmahabharatapi873664F6
            - /
            - Ref: CreateMahabaratAWSResourcesmahabharatapiDeploymentStageprod79B2FA4E
            - /GET/mahabharat-character-map
    Metadata:
      aws:cdk:path: CreateMahabaratAWSResourcesStack/CreateMahabaratAWSResources/mahabharat-api/Default/mahabharat-character-map/GET/ApiPermission.CreateMahabaratAWSResourcesStackCreateMahabaratAWSResourcesmahabharatapiCBFC22B3.GET..mahabharat-character-map
  CreateMahabaratAWSResourcesmahabharatapimahabharatcharactermapGETApiPermissionTestCreateMahabaratAWSResourcesStackCreateMahabaratAWSResourcesmahabharatapiCBFC22B3GETmahabharatcharactermap8839501F:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName:
        Fn::GetAtt:
          - CreateMahabaratAWSResourcesmultipurposeapilambdamahabharatgetcharactermap0A63BDCC
          - Arn
      Principal: apigateway.amazonaws.com
      SourceArn:
        Fn::Join:
          - ""
          - - "arn:"
            - Ref: AWS::Partition
            - ":execute-api:ap-southeast-2:"
            - Ref: AWS::AccountId
            - ":"
            - Ref: CreateMahabaratAWSResourcesmahabharatapi873664F6
            - /test-invoke-stage/GET/mahabharat-character-map
    Metadata:
      aws:cdk:path: CreateMahabaratAWSResourcesStack/CreateMahabaratAWSResources/mahabharat-api/Default/mahabharat-character-map/GET/ApiPermission.Test.CreateMahabaratAWSResourcesStackCreateMahabaratAWSResourcesmahabharatapiCBFC22B3.GET..mahabharat-character-map
  CreateMahabaratAWSResourcesmahabharatapimahabharatcharactermapGET1B49E0BC:
    Type: AWS::ApiGateway::Method
    Properties:
      HttpMethod: GET
      ResourceId:
        Ref: CreateMahabaratAWSResourcesmahabharatapimahabharatcharactermapEB3E8AE3
      RestApiId:
        Ref: CreateMahabaratAWSResourcesmahabharatapi873664F6
      AuthorizationType: NONE
      Integration:
        IntegrationHttpMethod: POST
        Type: AWS_PROXY
        Uri:
          Fn::Join:
            - ""
            - - "arn:"
              - Ref: AWS::Partition
              - :apigateway:ap-southeast-2:lambda:path/2015-03-31/functions/
              - Fn::GetAtt:
                  - CreateMahabaratAWSResourcesmultipurposeapilambdamahabharatgetcharactermap0A63BDCC
                  - Arn
              - /invocations
    Metadata:
      aws:cdk:path: CreateMahabaratAWSResourcesStack/CreateMahabaratAWSResources/mahabharat-api/Default/mahabharat-character-map/GET/Resource
  CDKMetadata:
    Type: AWS::CDK::Metadata
    Properties:
      Modules: aws-cdk=1.80.0,@aws-cdk/assets=1.80.0,@aws-cdk/aws-apigateway=1.80.0,@aws-cdk/aws-applicationautoscaling=1.80.0,@aws-cdk/aws-autoscaling-common=1.80.0,@aws-cdk/aws-cloudwatch=1.80.0,@aws-cdk/aws-codeguruprofiler=1.80.0,@aws-cdk/aws-dynamodb=1.80.0,@aws-cdk/aws-ec2=1.80.0,@aws-cdk/aws-ecr=1.80.0,@aws-cdk/aws-ecr-assets=1.80.0,@aws-cdk/aws-events=1.80.0,@aws-cdk/aws-iam=1.80.0,@aws-cdk/aws-kms=1.80.0,@aws-cdk/aws-lambda=1.80.0,@aws-cdk/aws-logs=1.80.0,@aws-cdk/aws-s3=1.80.0,@aws-cdk/aws-s3-assets=1.80.0,@aws-cdk/aws-sqs=1.80.0,@aws-cdk/aws-ssm=1.80.0,@aws-cdk/cloud-assembly-schema=1.80.0,@aws-cdk/core=1.80.0,@aws-cdk/custom-resources=1.80.0,@aws-cdk/cx-api=1.80.0,@aws-cdk/region-info=1.80.0,jsii-runtime=node.js/v10.13.0
    Metadata:
      aws:cdk:path: CreateMahabaratAWSResourcesStack/CDKMetadata/Default
Outputs:
  CreateMahabaratAWSResourcesmahabharatapiEndpoint678308FE:
    Value:
      Fn::Join:
        - ""
        - - https://
          - Ref: CreateMahabaratAWSResourcesmahabharatapi873664F6
          - .execute-api.ap-southeast-2.
          - Ref: AWS::URLSuffix
          - /
          - Ref: CreateMahabaratAWSResourcesmahabharatapiDeploymentStageprod79B2FA4E
          - /
  MahabharatcharactermapURL:
    Value:
      Fn::Join:
        - ""
        - - https://
          - Ref: CreateMahabaratAWSResourcesmahabharatapi873664F6
          - .execute-api.ap-southeast-2.amazonaws.com/mahabharat-character-map
Parameters:
  AssetParameters50e5446594261ec166609ce16e76ca70754ddbb6a26eabee651fc1fae286d403S3Bucket5D28E9B0:
    Type: String
    Description: S3 bucket for asset "50e5446594261ec166609ce16e76ca70754ddbb6a26eabee651fc1fae286d403"
  AssetParameters50e5446594261ec166609ce16e76ca70754ddbb6a26eabee651fc1fae286d403S3VersionKey4A90999D:
    Type: String
    Description: S3 key for asset version "50e5446594261ec166609ce16e76ca70754ddbb6a26eabee651fc1fae286d403"
  AssetParameters50e5446594261ec166609ce16e76ca70754ddbb6a26eabee651fc1fae286d403ArtifactHashF7A9D1C6:
    Type: String
    Description: Artifact hash for asset "50e5446594261ec166609ce16e76ca70754ddbb6a26eabee651fc1fae286d403"

